### ISSUE TITLE
Kassandra deconvolution

### ISSUE THREAD

**Issue by Elisa89m** [BostonGene/Kassandra#1]
Hi, 
I'm trying to use the Kassandra deconvolution tool, I already tried the web application,  but I'm wondering if kassandra tool can be also run by command line. What is the code that I can use to predict cell population?

Thanks in advance.

Elisa

**Comment by shpakb** [comment]
Hi Elisa! 

There is no command line version of Kassandra at the moment. You can train your own deconvolution model using code in this repository and the data provided on the Kassandra web page.
