### ISSUE TITLE
No deconvolution results?

### ISSUE THREAD

**Issue by Leelab-623** [BostonGene/Kassandra#2]
Hi! I submitted a file on your webpage a few days ago, but I have yet to receive the result. I wonder if it's a complicated algorithm that takes days to run? Will there be a command line version?

Also, I think the 30Mb requirement seems a bit too strict, especially for large datasets. Furthermore, the input format seems to be too narrow and too strict (i.e. Kallisto-processed transcript files). Would it be possible to validate your algorithm and see whether other pipelines work?

**Comment by shpakb** [comment]
Hi @Leelab-623! 
There was a bag in the web application. Please try again. It should work now. 

I think 30mb file limit has something to do with web application. I will ask web devs if they can fix that. In the meantime you can split your dataset by 10-20 samples and calculate it in batches.  

Kassandra is trained on a particular type of data which is Kallisto aligned transcripts (see publication for the details). You can use both per-gene and per-transcript quantities. It is hard to tell how well Kassandra will perform on data produced with other quantification tools. Newer actually tested that.
