### ISSUE TITLE
Kassandra Potential to detect rare cell population 

### ISSUE THREAD

**Issue by UboCA** [BostonGene/Kassandra#4]
Hi, I'm excited for your amazing training model.

Since Kassandra has got 51 unique cell subpopulations, of which I did not see some rare cell typeS, such as innate lymphoid cell(ILC, excluding NK), γδT，NKT... But there are more emerging evidence to show these cells also play an important role in TME.

So, I wonder if the builders of KS have detected or just tried to get some of these rare cell types. 

Indeed, deconvolution of these cell types will be very difficult for their less number or confusing transcriptomes(like ILCs are mirror to T helper cells). However, I'm still preserved for my opinion and glad to see yours.

Thanks advance for your reply.

**Comment by shpakb** [comment]
Hi there,

Thank you for your insightful comments and interest in Kassandra.

Indeed, detecting rare cell types can be quite challenging due low presence in the tissue and overlapping expression profiles. But actually we have already demonstrated our algorithm can detect rarer cell types such as Th1, Th2, and Th17 which we showed in our publication. Now we are in the process of adding capabilities for deconvolution of additional important rare cell types, including some you've mentioned. 

Cheers!
