### ISSUE TITLE
Kassandra model training

### ISSUE THREAD

**Issue by Candlelight-XYJ** [BostonGene/Kassandra#5]
Hi, I'm a new user of Kassandra, 
When I use these codes and training data downloaded from your website, it showed many errors for model training...
I was wondering if Kassandra could provide a well-trained model? 

Thanks a lot!

**Comment by shpakb** [comment]
Hi there,

I'd like to clarify that the code provided in this repository is meant to serve as an example of how the model is trained. There might be a few bugs in the code, will see what we can do. 

As for a well-trained model, you can definitely use ours. Please visit our [website](https://science.bostongene.com/kassandra/tool), where you can upload your data and use models we showed in publication.
