### ISSUE TITLE
Secure Connection Failed 

### ISSUE THREAD

**Issue by ConYel** [BostonGene/Kassandra#8]
Hello,
I am trying to reach the https://science.bostongene.com/kassandra/downloads
but I am getting:

> Secure Connection Failed
> 
> An error occurred during a connection to science.bostongene.com. PR_END_OF_FILE_ERROR
> 
> Error code: PR_END_OF_FILE_ERROR
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

Is there another way to get these downloads?

Thank you for your time

**Comment by jsangalang** [comment]
Perhaps there's a firewall block, preventing you from accessing the page? It works fine with me.

**Comment by yuandyuand13** [comment]
I have also encountered similar problems. When I clicked the link of the laboratory_data_expressions.tsv, it went to the web page “ https://science.bostongene.com/undefined/download/laboratory_data_expressions.tsv ”, and nothing was returned.

**Comment by shpakb** [comment]
Hello everyone, 
All data downloading issues have been resolved. Everything should work now.

Cheers!
